name: arborizacao
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  http: ^1.1.0 
  geolocator: ^10.1.0
  location: ^5.0.3
  font_awesome_flutter: ^10.6.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  flutter_map_location_marker: ^8.0.2
  fluttertoast: ^8.2.4
  page_animation_transition: ^1.0.0
  path_provider: ^2.1.1
  pdf: ^3.10.6
  open_file: ^3.3.2
  url_launcher: ^6.2.1  
  flutter_slide_drawer: ^1.0.3
  lottie: ^2.7.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  flutter_typeahead: ^5.0.1
  csv: ^5.1.1 
  step_progress_indicator: ^1.0.2
  image_picker: ^1.0.7 
  connectivity_plus: ^5.0.2
  dropdown_button2: ^2.3.9
  uuid: ^4.2.2
  pie_chart: ^5.4.0
  fl_chart: ^0.66.0
  mask_text_input_formatter: ^2.8.0 
  flutter_math_fork: ^0.7.2
  intl: ^0.19.0 
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/tree_home.png
    - assets/images/loading.json 
    - assets/images/not_found_point.json
    - assets/images/search.json
    - assets/images/city.json
    - assets/images/charts.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700